### ISSUE TITLE
想要拉取minio

### ISSUE THREAD

**Issue by 011011100** [2434017367/minio-serve-java#1]
我对这个项目进行了fork但是在git clone 中显示我没用证书

**Comment by elonehoo** [comment]
中文版本：我想我需要看到提示信息才能对于您的问题进行解决

English version: I think I need to see some prompts in order to solve your problem.

**Comment by 011011100** [comment]
好的这是我提供的git报错信息
![image](https://user-images.githubusercontent.com/74953343/226863255-a262d6a7-d6e2-4485-b7db-2db38eed6997.png)

**Comment by 011011100** [comment]
当我fork了这个仓库之后进行拉取依然会出现这个错误

**Comment by elonehoo** [comment]
中文版本：
1. 我想你应该fork完这个仓库
2. clone 自己的[仓库链接](https://github.com/011011100/minio-serve-java)
3. 修改完之后提交到自己fork的仓库，然后提出PR

English version:
1. I think you should fork this repository first.
2. Clone your own [repository link](https://github.com/011011100/minio-serve-java).
3. After making changes, submit them to your forked repository and then create a pull request.

**Comment by 011011100** [comment]
😒
![image](https://user-images.githubusercontent.com/74953343/226865315-3d60114d-8fe4-41cb-b54d-6367aa442ae5.png)

**Comment by elonehoo** [comment]
是否可以将你的git生成的key填入GitHub呢

**Comment by elonehoo** [comment]
https://docs.github.com/zh/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

**Comment by 011011100** [comment]
令人费解
![image](https://user-images.githubusercontent.com/74953343/226889631-03645de4-a416-42dd-bc42-724fa1bdc221.png)
上面的图片显示我已经有ssh证书并且跟github完成了绑定
同时我还使用git对GitHub进行了ssh连接测试
结果如下
![image](https://user-images.githubusercontent.com/74953343/226889963-38423720-cb39-4fa0-af2b-203f3941b440.png)
符合标准
但是任然出现了问题
![image](https://user-images.githubusercontent.com/74953343/226890062-0592f32e-1afa-403e-a6b1-64421a13a084.png)
chatGPT的解释是这样的
![image](https://user-images.githubusercontent.com/74953343/226890154-bbfcf093-8214-4f1d-b0d0-54250e3a6257.png)
但是当我进行过了连接测试并成功之后还是出现了这样的问题就很怪

**Comment by elonehoo** [comment]
是否可以不使用vscode，而是使用命令行去clone项目

**Comment by 011011100** [comment]
我搞定了傻逼vscode

**Comment by 011011100** [comment]
晦气此贴终结
